### ISSUE TITLE
Wrong path if same "key: value" exists on other nested path

### ISSUE THREAD

**Issue by enkol** [CYBAI/vscode-yaml-key-viewer#1]
```yaml
first:
  cancel: 'Cancel'

second:
  cancel: 'Cancel'
```

With cursor on line 5, "YAML: Get full key" returns `first.cancel`, instead of `second.cancel`.
