### ISSUE TITLE
YAML: full key copy/get is sometime wrong 

### ISSUE THREAD

**Issue by MrLuje** [CYBAI/vscode-yaml-key-viewer#17]
First, thanks for the extension, it is really a time saver :)

* Take the following yaml :
```yaml
quarkus:
  kafka:
    health:
      enabled: true
```
* Use `Get full key` or `Copy full key to clipboard` on the last line (`enabled` tag)
* Resulting value is `kafka.health.quarkus.enabled` instead of `quarkus.kafka.health.enabled`
